// <auto-generated />
using System;
using Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(TheApiDbContext))]
    partial class TheApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Entities.DiskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long>("CapacityGb")
                        .HasColumnType("bigint");

                    b.Property<string>("DiskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MountPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<long>("UsedGb")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ServerId"), new[] { "Id", "MountPoint", "CapacityGb", "DiskType", "UsedGb" });

                    b.ToTable("Disks");
                });

            modelBuilder.Entity("Common.Entities.InstalledServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ServerId"), new[] { "Id", "Name", "Version", "Port", "Status", "InstalledAt" });

                    b.ToTable("InstalledServices");
                });

            modelBuilder.Entity("Common.Entities.NetworkInterfaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("SubnetMask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ServerId"), new[] { "Id", "Name", "MacAddress", "IpAddress", "SubnetMask", "VlanId", "IsEnabled" });

                    b.ToTable("NetworkInterfaces");
                });

            modelBuilder.Entity("Common.Entities.ServerEntity", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int>("CpuCores")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecommissionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("MemoryMb")
                        .HasColumnType("int");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ProvisionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RowId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Common.Entities.ServerJsonEntity", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int>("CpuCores")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecommissionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("MemoryMb")
                        .HasColumnType("int");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ProvisionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RowId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ServersJson");
                });

            modelBuilder.Entity("Common.Entities.ServerTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ServerId"), new[] { "Id", "Key", "Value" });

                    b.ToTable("ServerTags");
                });

            modelBuilder.Entity("Common.Entities.DiskEntity", b =>
                {
                    b.HasOne("Common.Entities.ServerEntity", "Server")
                        .WithMany("Disks")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Common.Entities.InstalledServiceEntity", b =>
                {
                    b.HasOne("Common.Entities.ServerEntity", "Server")
                        .WithMany("InstalledServices")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Common.Entities.NetworkInterfaceEntity", b =>
                {
                    b.HasOne("Common.Entities.ServerEntity", "Server")
                        .WithMany("NetworkInterfaces")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Common.Entities.ServerJsonEntity", b =>
                {
                    b.OwnsMany("Common.Entities.DiskJson", "Disks", b1 =>
                        {
                            b1.Property<int>("ServerJsonEntityRowId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<long>("CapacityGb");

                            b1.Property<string>("DiskType")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("MountPoint")
                                .IsRequired();

                            b1.Property<long>("UsedGb");

                            b1.HasKey("ServerJsonEntityRowId", "__synthesizedOrdinal");

                            b1.ToTable("ServersJson");

                            b1
                                .ToJson("Disks")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ServerJsonEntityRowId");
                        });

                    b.OwnsMany("Common.Entities.InstalledServiceJson", "InstalledServices", b1 =>
                        {
                            b1.Property<int>("ServerJsonEntityRowId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("Id");

                            b1.Property<DateTime>("InstalledAt");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("Port");

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.Property<string>("Version")
                                .IsRequired();

                            b1.HasKey("ServerJsonEntityRowId", "__synthesizedOrdinal");

                            b1.ToTable("ServersJson");

                            b1
                                .ToJson("InstalledServices")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ServerJsonEntityRowId");
                        });

                    b.OwnsMany("Common.Entities.NetworkInterfaceJson", "NetworkInterfaces", b1 =>
                        {
                            b1.Property<int>("ServerJsonEntityRowId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("IpAddress");

                            b1.Property<bool>("IsEnabled");

                            b1.Property<string>("MacAddress")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("SubnetMask");

                            b1.Property<int?>("VlanId");

                            b1.HasKey("ServerJsonEntityRowId", "__synthesizedOrdinal");

                            b1.ToTable("ServersJson");

                            b1
                                .ToJson("NetworkInterfaces")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ServerJsonEntityRowId");
                        });

                    b.OwnsMany("Common.Entities.ServerTagJson", "Tags", b1 =>
                        {
                            b1.Property<int>("ServerJsonEntityRowId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ServerJsonEntityRowId", "__synthesizedOrdinal");

                            b1.ToTable("ServersJson");

                            b1
                                .ToJson("Tags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ServerJsonEntityRowId");
                        });

                    b.Navigation("Disks");

                    b.Navigation("InstalledServices");

                    b.Navigation("NetworkInterfaces");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Common.Entities.ServerTagEntity", b =>
                {
                    b.HasOne("Common.Entities.ServerEntity", "Server")
                        .WithMany("Tags")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Common.Entities.ServerEntity", b =>
                {
                    b.Navigation("Disks");

                    b.Navigation("InstalledServices");

                    b.Navigation("NetworkInterfaces");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
